const models = [
  "Acura RLX",
  "Alfa Romeo Mito",
  "Aston Martin DBX",
  "Audi A6 Quattro",
  "Audi Q3 Sport",
  "Bentley Continental",
  "BMW 5 Sport Gran",
  "BMW 7 xDrive",
  "Chevrolet Camaro",
  "Chevrolet Impala",
  "Citroen C5",
  "Citroen C4 Grand",
  "Cupra Formentor",
  "Dodge Challenger",
  "Ferrari Portofino",
  "Fiat Lounge Mini",
  "Fiat Panda Cross",
  "Ford C-Max",
  "Ford Explorer",
  "Ford Mustang",
  "Genesis GV80",
  "Honda Civic DX",
  "Hyundai Elantra",
  "Infiniti QX80",
  "Jaguar F-Pace",
  "Jeep Grand Cherokee",
  "Kia Sportage",
  "Kia Stinger",
  "Lexus GS 350",
  "Lincoln Navigator",
  "Maserati Levante",
  "Mazda CX-5",
  "Mazda 6 Dynamique",
  "Mercedes C300 AMG",
  "Mercedes Citan",
  "Mitsubishi Lancer",
  "Nissan Touring",
  "Opel Astra Sport",
  "Opel Vivaro",
  "Peugeot 508 Allure",
  "Peugeot Boxer PRO",
  "Porsche 911 Carrera",
  "Renault Grand Scenic",
  "Skoda Octavia RS",
  "Subaru BRZ Sport",
  "Suzuki SX4 S-Cross",
  "Toyota Camry",
  "Toyota Corolla",
  "Toyota Sequoia",
  "Volkswagen Crafter",
  "Volkswagen Polo",
  "Volvo S60",
  "Volvo XC90",
  "LADA Vesta SW",
  "LADA XRAY",
  "LADA Granta",
];

export default models;
